import Layout from "@/components/Layout";
import { BasketProvider } from "@/context/BasketContext";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import CustomPacket from "../components/CustomPacket";

export default function Home() {
  return (
    <>
      <Head>
        <title>beije</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <BasketProvider>
          <Layout>
            <CustomPacket />
          </Layout>
        </BasketProvider>
      </main>
    </>
  );
}
